### ISSUE TITLE
Jamming of L1 band

### ISSUE THREAD

**Issue by neerajseth000** [mossmann/hackrf#493]
Hey
I am using Hack-rf device for Jamming of GPS L1 band for my project. While jamming L1 band I have seen it also affects othe bands. Could anyone suggest , whether it has harmonics falling in other bands as well or not etc.

**Comment by mossmann** [comment]
It is illegal to jam in the United States and probably most other countries.  You should only do such an experiment inside a shielded chamber.

Because of the dual-conversion architecture, HackRF One will produce a lower power image on the opposite side of the IF.  This should be somewhere around 4 GHz if you are tuned to 1.5 GHz.  There will also be a lower power image at the IF which is between 2.15 and 2.75 GHz (probably around 2.6 GHz when you are tuned to 1.5 GHz if I remember correctly).  There are also images produced by harmonics of the local oscillator.  For example, if you are tuned to 1.5 GHz with an IF of 2.6 GHz, the front-end LO is 1.1 GHz; one harmonic of that is 2.2 GHz which results in an image at 2.6-2.2=0.4 GHz.  If you use the hackrf_transfer utility you can precisely control the IF which affects the frequency of all such images.

To minimize images produced by aliasing, you should use the highest sample rate you can and the lowest analog baseband filter bandwidth you can.

Another way to reduce images is to reduce your output power as much as your experiment allows.  Typically you should maximize power in the digital domain (to improve SNR) and then use as little analog amplification (-x and -a options on hackrf_transfer) as you can.

You can use a spectrum analyzer (or another HackRF with hackrf_sweep) to detect and measure images.
