### ISSUE TITLE
Signal Strength Misrepresented in qspectrumanalyzer for 0GHz-2.1GHz

### ISSUE THREAD

**Issue by phlogistic** [mossmann/hackrf#506]
Seen this behavior in multiple different physical locations. Same laptop, shielded / ferrite core monoprice USB cable, same hackRF in different locations.

![2ghzdropoff](https://user-images.githubusercontent.com/1087662/43324516-51e67e96-9182-11e8-84f3-f30d03a3bc2f.png)

![dropoff2ghz](https://user-images.githubusercontent.com/1087662/43324539-64564bba-9182-11e8-83da-48f51e2d10de.png)

### Steps to reproduce
1. Install qspectrumanalyzer
2. Update firmware on hackRF to 2nd to latest firmware release, if necessary
3. Use hackRF to sweep 20MHz-6GHz
4. See 20MHz-2.1GHz is misrepresented for signal strength
5. Confirm by going to multiple different physical locations

### Expected behaviour
20MHz-2.1GHz signal strength is not a plateau

### Actual behaviour
20MHz-2.1GHz signal strength is a plateau

### Version information
**Operating system**:

Ubuntu 16.04.1

**hackrf_info output:**

TBD

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

qspectrumanalyzer 2.1.0

**Comment by dominicgs** [comment]
What sort of antenna do you have connected to your HackRF?

While that step is very abrupt, it's at a point where we change RF paths and we would expect there to be some change in signal strength because the different RF paths have different characteristics.

I'm more concerned that there appear to be no distinct signals showing up anywhere in the entire sweep.  I would normally expect there to be some signals showing and the noise floor between -60 and -70 dB.  However, you appear to have very specific levels in the colour levels chart on the right.

**Comment by phlogistic** [comment]
ANT500

**Comment by konikofi** [comment]
Looks like ANT500 is rated for 75MHz to 1GHz.
https://www.adafruit.com/product/3584

**Comment by dominicgs** [comment]
@phlogistic As we discussed in person at defcon, the ~3 dB drop at the frequency where we switch RF paths is not unexpected.

However, the completely flat performance across the rest of the frequency range suggests an issue.  Can you try running this again with a different antenna?  Even a piece of wire or an unfurled paperclip would do for testing.
