### ISSUE TITLE
Changing the antenna port bias voltage

### ISSUE THREAD

**Issue by RChadwick7** [mossmann/hackrf#643]
It appears the antenna Bias voltage is 3.3v at very low current, but all the amplifiers I want to use are 5v, and Tx amplifiers often want more current. Is there a reason 3.3v was chosen for the bias voltage? If I were to replace Q4 and L13 with parts that can handle an Amp, and connect the Source of Q4 to 5V through a PTC or fuse, I could get a 5V 800mA bias. Are there any downsides I'm not seeing?

**Comment by miek** [comment]
As far as I know, the bias function was added because it was easy to tap off the 3.3V supply that was already there. Routing the 5V supply over there would've added a lot of complexity and risk of coupling noise into the frontend.
Other than possibly introducing a lot of noise from the USB supply, I don't see any obvious gotchas with the mod, but it's on you if you want to take the risk!
