### ISSUE TITLE
HackRF TX amplifier question

### ISSUE THREAD

**Issue by SakurabaKiyoka** [mossmann/hackrf#735]
My hackrf RX amplifier works well,but when I use TX with amplifier,I got weaker signal instead of boost signal.I use the USB-current meter to see the current.when i close the amp,it costs 0.26A with 47dbm IF gain.when i open the amp,weaker signal but it costs 0.35A with 47dbm IF gain.does the amplifier broken?but it works well in RX mode.

**Comment by miek** [comment]
Yes, this does sound like the TX amplifier is broken. The TX and RX amps are two separate parts, so they can fail individually.
It should work fine otherwise if you don't need to use the TX amp but, if you got your HackRF One from one of the official resellers, you can arrange with them for a replacement.
