### ISSUE TITLE
How to implement Multiple Frequency-Transmission on HackRF

### ISSUE THREAD

**Issue by raymondcarlpchua** [mossmann/hackrf#742]
Good day! It is possible to simultaneously transmit multiple radio frequency using HackRF One? How? If not, it is possible to create a separate GNU radio flowgraph files and then transmit it one by one? I was able to transmit to a single frequency ( see the attached file). Did I miss something on my flowgraph in order to transmit in multiple radio frequency? 
<img width="641" alt="Capture" src="https://user-images.githubusercontent.com/59864768/83377826-6be43400-a409-11ea-8441-931a795ff8f7.PNG">

**Comment by CvMaRTY** [comment]
This is from GNURadio:
![FM_transmitter_multiple_stations](https://user-images.githubusercontent.com/10252183/96631867-8fa80800-131f-11eb-970a-35e5e0fabf6d.png)

I tried a different approach though. And this is because the WBFM transmit cuts everything over 16KHz, but I wanted to input MPX signal so it can also have Stereo & RDS. Both frequencies had very good modulation, but I was worried about the harmonics that I haven't solved yet.
![LIVE_FM_STATION_MPX grc](https://user-images.githubusercontent.com/10252183/96632327-342a4a00-1320-11eb-896b-def4d2a9d17e.png)

**Comment by straithe** [comment]
Do you still need help with your question?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
