### ISSUE TITLE
Different connector than USB

### ISSUE THREAD

**Issue by alemanydavid** [mossmann/hackrf#810]
Is there any possibility to connect the HackRF One with another connector than USB to get more distance?
Maybe using any type of conversor to change between USB and ethernet.

It is works? Or I need a connector which provides power too?

**Comment by mossmann** [comment]
Yes, you would need to provide power. There are some folks who have used off-the-shelf or DIY USB extender solutions, but we have seen people destroy their HackRF Ones this way due to ground loops! In theory Power-Over-Ethernet would be a great solution, but you would need some way to convert from Ethernet to USB for the data transport. One way to do so would be with a single-board Linux computer that provides access to the HackRF One via [SoapyRemote](https://github.com/pothosware/SoapyRemote) or similar.
