### ISSUE TITLE
How to hardware-disable the transmit-capability on HackRF

### ISSUE THREAD

**Issue by cjh08052** [mossmann/hackrf#841]
I currently own a HackRF One and need to use it in an environment where I must hardware-disable the RF transmitter. I tried looking through post and Google-ing for any info; but I'm sure most people do not have such a restriction. Boy-scouts honour of 'I simply will not transmit' is not going to be good enough.

  Is there a way to hardware-disable the transmitter on the HackRF. I'm willing to solder/desolder and even cut traces as needed. I would prefer a reversible solution, but if one does not exist that's fine.

### Steps to reproduce
N/A

### Expected behaviour
The HackRF will no longer be able to transmit.

**Comment by mossmann** [comment]
There are several ways to accomplish this, but I think the cleanest reversible method would be to desolder components C8 and L12:
![image](https://user-images.githubusercontent.com/1195107/109556007-7e23f900-7a93-11eb-9ad0-e1913cea6920.png)

Removal of C8 will block (most of) the signal transmitted by the intermediate frequency (IF) transceiver. Removal of L12 will prevent the transmit RF amplifier from being powered (which could otherwise amplify a very weak signal up to detectable levels). With these modifications, the unit will still appear to transmit, but any transmitted signal should be too weak to detect.

**Comment by straithe** [comment]
How did desoldering the components work out for you, @cjh08052 ?

**Comment by cjh08052** [comment]
Thanks for checking in on me and this effort. We have not gotten approval to to use the radio nor modify it yet. It's been uphill.On Apr 23, 2021 7:34 PM, Straithe ***@***.***> wrote:
How did desoldering the components work out for you, @cjh08052 ?

**Comment by straithe** [comment]
I'm going to close this issue as desoldering the components should work and it seems like it might take a while for you to test things. Please re-open this issue, or open a new issue referencing this one if the provided solution doesn't work.
