### ISSUE TITLE
PortaPack H2+ incompatible with my HackRF One?

### ISSUE THREAD

**Issue by edwardstorlien** [mossmann/hackrf#884]
**Describe the bug**
I just got my new Portapack H2+ clone from AliExpress to use with my HackRF One clone. I have flashed the Mayhem firmware, and the HackRF boots just fine. The problem is that the display does not change when I try to scroll or click the buttons. It always shows the start menu. I have also tried the original Portapack firmware, but the problem is still the same.

I know that the HackRF works with the buttons and scroll wheel, because I can enter the receive mode and the Rx light will illuminate. But the display still shows the start menu. I can also scroll down (without actually seeing it scrolling down) to the option where I can use the HackRF with a computer over USB. When I enter that option, the display does turn blue and show the block diagram of the HackRF. It even shows the correct frequency and gain when I use software such as SDR Sharp.

I have tried the Portapack board with my friend's genuine HackRF One, and it works all fine. I also tried it with the original Portapack firmware. Therefore I think I can conclude that the problem lies in my HackRF, but the HackRF works all fine through a computer. Never experienced any problems, and it still works fine.

What could the problem be? Could there be some incompatibility between my HackRF One and the Portapack, since it works on my friend's?

**Information**
My HackRF One is a clone, and labeled 13 February 2014 on the PCB.
I have tried the latest Mayhem firmware (ver. 1.4.0), 1.3.1 and 1.2.0
I have also tried the original Portapack firmware

**Comment by straithe** [comment]
It is possible that there could be incompatibility between your HackRF One clone and Portapack H2. We have seen other GitHub issues raising similar problems between Portapack H2 and HackRF One clones. Unfortunately we don't have much insight into these incompatibility issues since there are so many different Portapack H2 producers and HackRF One clones and buying and testing each of these combinations would be very time consuming. 

 What I can suggest is ensuring that your HackRF firmware is on the [latest release](https://github.com/mossmann/hackrf/releases/tag/v2021.03.1). You may also want to talk to the seller of your HackRF clone to see if they offer technical support for the boards they produce. 

Good luck!
